### ISSUE TITLE
Included examples?

### ISSUE THREAD

**Issue by klaasdc** [amperpirat/MAX41460-Arduino-Library#2]
Hi,

In the readme, there is a mention of the examples:

_4. For a how-to just have a look into the examples; they're small and cover only one piece of the device_

Could it be that they are left out? I'm very interested to take a look.

**Comment by amperpirat** [comment]
Hi Klaas,

thanks a lot for your message. Unfortunately - due to time constraints - I never got to the point to write and publish examples for an Arduino environment. 

Best regards,
Ole
